[package]
name = "vision-core"
version.workspace = true
edition.workspace = true

[dependencies]
tokio-stream = "0.1.19"
tonic = "0.14.6"
vision-proto = { path = "../vision-proto" }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net", "time"] }
tokio-stream = { version = "0.1.19", features = ["net"] }
